version: '2.2'
services:
  app:
    image: nginx:alpine
    volumes:
      - ./app:/usr/share/nginx/html
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  nightwatch:
    image: blueimp/nightwatch:0.9
    init: true
    depends_on:
      - chromedriver
      - app
    environment:
      - WAIT_FOR_HOSTS=app:80 chromedriver:4444 chromedriver:6060
    volumes:
      - ./test:/home/node
